61 always upload artifact (#63)
* Artifact upload runs always, and scheduled nightly test runs only if master changed in the last 24 hours
* Changed echo to printf

diff --git a/.github/workflows/test_nightly.yml b/.github/workflows/test_nightly.yml
--- a/.github/workflows/test_nightly.yml
+++ b/.github/workflows/test_nightly.yml
@@ -1,13 +1,27 @@
-name: Nosetests
+name: Nosetests and Valgrind
 
 on:
   schedule:
-    - cron: '0 16 * * 1-5'  # On weekdays at UTC 16:00
+    - cron: '0 16 * * *'  # Daily at UTC 16:00
 
 jobs:
+  iftest:
+    runs-on: [self-hosted, linux]
+    outputs:
+      should_run: ${{ steps.store_output.outputs.SHOULD_RUN }}
+    steps:
+    - name: Checkout 🛎
+      uses: actions/checkout@v2
+      with:
+        path: main_class
+    - name: Store output
+      id: store_output
+      run: cd main_class && echo ::set-output name=SHOULD_RUN::$(( $(git --no-pager log -1 --format=%at) - $(date +%s) + 86400 ))
+
   nose_tests_lvl3:
     runs-on: [self-hosted, linux, heavy]
-
+    needs: iftest
+    if: needs.iftest.outputs.should_run > 0
     steps:
     - name: Checkout 🛎
       uses: actions/checkout@v2
@@ -23,17 +37,20 @@ jobs:
         cd main_class/python
         COMPARE_OUTPUT_GAUGE=1 TEST_LEVEL=3 nosetests -v -a test_scenario test_class.py
     - name: Upload plots 📤
+      if: success() || failure()
       uses: actions/upload-artifact@v2
       with:
         name: ComparePlots
         path: main_class/python/faulty_figs
     - name: Remove virtual Python environment
+      if: success() || failure()
       run: rm -rf venv
 
-  valgrind:
+  valgrind-wide-and-shallow:
     runs-on: [self-hosted, linux, heavy]
+    needs: iftest
+    if: needs.iftest.outputs.should_run > 0
     timeout-minutes: 720
-
     steps:
     - name: Checkout 🛎
       uses: actions/checkout@v2
@@ -47,8 +64,48 @@ jobs:
       run: |
         source venv/bin/activate
         cd main_class/python
-        TEST_LEVEL=2 CLASS_VERBOSE=1 nosetests -a dump_ini_files test_class.py
+        TEST_LEVEL=3 CLASS_VERBOSE=1 nosetests -a dump_ini_files test_class.py
     - name: Remove virtual Python environment
+      if: success() || failure()
+      run: rm -rf venv
+    - name: Valgrind 🤖
+      run: |
+        cd main_class/python/faulty_figs
+        rm -rf output && mkdir output
+        rm -rf valgrind_output && mkdir valgrind_output
+        cp ../../class .
+        printf "\nk_step_sub = 10.0\nk_step_super = 0.4\nk_per_decade_for_pk = 2\nk_per_decade_for_bao = 5\n" >> *.ini
+        ls *.ini | xargs -I {} -n 1 -P 6 bash -c ': \
+          && (valgrind --leak-check=full --error-exitcode=3 ./class {} &> {}.out && echo {} "...ok") \
+          || (echo {} "...fail" && cp {}.* valgrind_output && exit 3)'
+    - name: Upload errors 📤
+      if: success() || failure()
+      uses: actions/upload-artifact@v2
+      with:
+        name: ValgrindOutputWideShallow
+        path: main_class/python/faulty_figs/valgrind_output
+
+  valgrind-narrow-and-deep:
+    runs-on: [self-hosted, linux, heavy]
+    needs: iftest
+    if: needs.iftest.outputs.should_run > 0
+    timeout-minutes: 720
+    steps:
+    - name: Checkout 🛎
+      uses: actions/checkout@v2
+      with:
+        path: main_class
+    - name: Create virtual Python environment
+      run: rm -rf venv && virtualenv venv --system-site-packages
+    - name: make
+      run: cd main_class && make -j
+    - name: Generate input files
+      run: |
+        source venv/bin/activate
+        cd main_class/python
+        TEST_LEVEL=1 CLASS_VERBOSE=1 nosetests -a dump_ini_files test_class.py
+    - name: Remove virtual Python environment
+      if: success() || failure()
       run: rm -rf venv
     - name: Valgrind 🤖
       run: |
@@ -60,7 +117,8 @@ jobs:
           && (valgrind --leak-check=full --error-exitcode=3 ./class {} &> {}.out && echo {} "...ok") \
           || (echo {} "...fail" && cp {}.* valgrind_output && exit 3)'
     - name: Upload errors 📤
+      if: success() || failure()
       uses: actions/upload-artifact@v2
       with:
-        name: ValgrindOutput
+        name: ValgrindOutputNarrowDeep
         path: main_class/python/faulty_figs/valgrind_output
